#!/bin/bash

function check_positive()
{
    # $1 represent number that we want to check
    if ! [[ "$1" =~ ^[0-9]+$ ]] || [ "$1" -eq 0 ]; then
        echo "Invalid input. Please enter a positive number."
        return 1
    fi

    return 0
}


function table_exits()
{
  if [[ -f "$1" ]]; then
    return 0 # Exists
  else
    echo "file not exist"
    return 1 # Does not exist
  fi
}



function check_range()
{
    # $1 number
    # $2 max number (range)
    if ! [[ "$1" -ge 1 && "$1" -le "$2" ]]; then
        
        echo "Invalid input. Please enter a number between 1 and $2."
        return 1
    fi
    return 0
}

function check_empty_string()
{
    if [ -z "$1" ]; then
            echo "Error: string is empty."
            return 1
    fi
    return 0
}


function check_starting_string()
{
    if ! [[ "$1" =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]]; then
        echo "Error: Column name must start with a letter "
            return 1
            
    fi
    return 0
}


function check_int()
{
    # $1 represent number that we want to check
    if ! [[ $1 =~ ^-?[0-9]+$ ]]; then
        echo "Invalid input. Please enter a valid number."
        return 1
    fi

    return 0
}